/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInquiry {
  'id' : bigint,
  'name' : string,
  'submittedAt' : bigint,
  'email' : string,
  'message' : string,
  'category' : InquiryCategory,
}
export type InquiryCategory = { 'Collaborations' : null } |
  { 'Retail' : null } |
  { 'BulkOrders' : null };
export interface Testimonial {
  'id' : bigint,
  'name' : string,
  'text' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'listInquiries' : ActorMethod<[], Array<ContactInquiry>>,
  'listTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'submitInquiry' : ActorMethod<
    [string, string, string, InquiryCategory],
    ContactInquiry
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];