/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const InquiryCategory = IDL.Variant({
  'Collaborations' : IDL.Null,
  'Retail' : IDL.Null,
  'BulkOrders' : IDL.Null,
});
export const ContactInquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'category' : InquiryCategory,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'text' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'listInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, InquiryCategory],
      [ContactInquiry],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const InquiryCategory = IDL.Variant({
    'Collaborations' : IDL.Null,
    'Retail' : IDL.Null,
    'BulkOrders' : IDL.Null,
  });
  const ContactInquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'category' : InquiryCategory,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'text' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'listInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'listTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, InquiryCategory],
        [ContactInquiry],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };